// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsqXKo3dySHDDMzvcd3MAVPFENhist-M',
    appId: '1:231886046583:web:406e64d42bce569cd34d72',
    messagingSenderId: '231886046583',
    projectId: 'candlelab-c846c',
    authDomain: 'candlelab-c846c.firebaseapp.com',
    storageBucket: 'candlelab-c846c.firebasestorage.app',
    measurementId: 'G-D3DMGGQL1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4GusJjjzlbGZdVD6Vo2gc3RzQyBikKo',
    appId: '1:231886046583:android:93c04d21260a1fb8d34d72',
    messagingSenderId: '231886046583',
    projectId: 'candlelab-c846c',
    storageBucket: 'candlelab-c846c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVQpxms8fAT26L2vT-B-oSIz52Y-E_07k',
    appId: '1:231886046583:ios:b8ec47ab1105c24ed34d72',
    messagingSenderId: '231886046583',
    projectId: 'candlelab-c846c',
    storageBucket: 'candlelab-c846c.firebasestorage.app',
    iosBundleId: 'com.example.candleLabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVQpxms8fAT26L2vT-B-oSIz52Y-E_07k',
    appId: '1:231886046583:ios:b8ec47ab1105c24ed34d72',
    messagingSenderId: '231886046583',
    projectId: 'candlelab-c846c',
    storageBucket: 'candlelab-c846c.firebasestorage.app',
    iosBundleId: 'com.example.candleLabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZsqXKo3dySHDDMzvcd3MAVPFENhist-M',
    appId: '1:231886046583:web:3bcdce3e905f7de4d34d72',
    messagingSenderId: '231886046583',
    projectId: 'candlelab-c846c',
    authDomain: 'candlelab-c846c.firebaseapp.com',
    storageBucket: 'candlelab-c846c.firebasestorage.app',
    measurementId: 'G-7TR8GDER1V',
  );
}
